[package]
name = "spdyboost"
version = "0.1.0"
authors = ["Laurens Devos <laurens.devos@outlook.com>"]
autobenches = false

[dependencies]
num = "0.2"
rand = "0.6.1"
flate2 = "1.0.6"
csv = "1.0.2"

log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }

#serde = "1.0"
#serde_derive = "1.0"
#toml = "0.4.10"

[dev-dependencies]
criterion = "0.2"
pretty_env_logger = "0.3.0" # examples

[[bench]]
name = "bitvec"
harness = false

[[bench]]
name = "bitslice"
harness = false
